### ISSUE TITLE
Processing Error

### ISSUE THREAD

**Issue by soumyaranjansabat** [vbartonicek/topuniversities-scraper#9]
2021-05-15T22:18:19.316Z ACTOR: Pulling Docker image from repository.
2021-05-15T22:18:20.330Z ACTOR: Creating Docker container.
2021-05-15T22:18:20.478Z ACTOR: Starting Docker container.
2021-05-15T22:18:23.224Z 
2021-05-15T22:18:23.225Z > topuniversities-scraper@0.0.1 start /home/myuser
2021-05-15T22:18:23.226Z > node src/index.js
2021-05-15T22:18:23.227Z 
2021-05-15T22:18:24.056Z INFO: System info {"apifyVersion":"0.19.1","apifyClientVersion":"0.5.26","osType":"Linux","nodeVersion":"v12.18.4"}
2021-05-15T22:18:24.065Z WARNING: You are using an outdated version (0.19.1) of Apify SDK. We recommend you to update to the latest version (1.0.2).
2021-05-15T22:18:24.066Z          Read more about Apify SDK versioning at: https://help.apify.com/en/articles/3184510-updates-and-versioning-of-apify-sdk
2021-05-15T22:18:25.810Z INFO: AutoscaledPool state {"currentConcurrency":0,"desiredConcurrency":2,"systemStatus":{"isSystemIdle":true,"memInfo":{"isOverloaded":false,"limitRatio":0.2,"actualRatio":null},"eventLoopInfo":{"isOverloaded":false,"limitRatio":0.4,"actualRatio":null},"cpuInfo":{"isOverloaded":false,"limitRatio":0.4,"actualRatio":null},"clientInfo":{"isOverloaded":false,"limitRatio":0.3,"actualRatio":null}}}
2021-05-15T22:18:25.930Z INFO: Launching Puppeteer {"headless":true,"args":["--no-sandbox","--user-agent=Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.79 Safari/537.36"],"timeout":15000,"defaultViewport":{"width":1366,"height":768}}
2021-05-15T22:18:31.024Z Processing https://www.topuniversities.com/university-rankings/world-university-rankings/2020...
2021-05-15T22:18:31.033Z ERROR: BasicCrawler: handleRequestFunction failed, reclaiming failed request back to the list or queue {"url":"https://www.topuniversities.com/university-rankings/world-university-rankings/2020","retryCount":1,"id":"UlzsCkFHx3fdCcC"}
2021-05-15T22:18:31.035Z   Error: No node found for selector: #qs-rankings_length select
2021-05-15T22:18:31.035Z     at Object.exports.assert (/home/myuser/node_modules/puppeteer/lib/cjs/puppeteer/common/assert.js:26:15)
2021-05-15T22:18:31.036Z     at DOMWorld.select (/home/myuser/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:294:21)
2021-05-15T22:18:31.037Z     at processTicksAndRejections (internal/process/task_queues.js:97:5)
2021-05-15T22:18:31.038Z     at async PuppeteerCrawler.handlePageFunction (/home/myuser/src/index.js:50:17)
2021-05-15T22:18:31.039Z     at async /home/myuser/node_modules/apify/build/utils.js:409:20
2021-05-15T22:18:46.618Z Processing https://www.topuniversities.com/university-rankings/world-university-rankings/2020...
2021-05-15T22:18:46.636Z ERROR: BasicCrawler: handleRequestFunction failed, reclaiming failed request back to the list or queue {"url":"https://www.topuniversities.com/university-rankings/world-university-rankings/2020","retryCount":2,"id":"UlzsCkFHx3fdCcC"}
2021-05-15T22:18:46.637Z   Error: No node found for selector: #qs-rankings_length select
2021-05-15T22:18:46.637Z     at Object.exports.assert (/home/myuser/node_modules/puppeteer/lib/cjs/puppeteer/common/assert.js:26:15)
2021-05-15T22:18:46.638Z     at DOMWorld.select (/home/myuser/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:294:21)
2021-05-15T22:18:46.639Z     at processTicksAndRejections (internal/process/task_queues.js:97:5)
2021-05-15T22:18:46.639Z     at async PuppeteerCrawler.handlePageFunction (/home/myuser/src/index.js:50:17)
2021-05-15T22:18:46.640Z     at async /home/myuser/node_modules/apify/build/utils.js:409:20
2021-05-15T22:19:00.539Z Processing https://www.topuniversities.com/university-rankings/world-university-rankings/2020...
2021-05-15T22:19:00.548Z ERROR: BasicCrawler: handleRequestFunction failed, reclaiming failed request back to the list or queue {"url":"https://www.topuniversities.com/university-rankings/world-university-rankings/2020","retryCount":3,"id":"UlzsCkFHx3fdCcC"}
2021-05-15T22:19:00.549Z   Error: No node found for selector: #qs-rankings_length select
2021-05-15T22:19:00.550Z     at Object.exports.assert (/home/myuser/node_modules/puppeteer/lib/cjs/puppeteer/common/assert.js:26:15)
2021-05-15T22:19:00.551Z     at DOMWorld.select (/home/myuser/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:294:21)
2021-05-15T22:19:00.551Z     at processTicksAndRejections (internal/process/task_queues.js:97:5)
2021-05-15T22:19:00.552Z     at async PuppeteerCrawler.handlePageFunction (/home/myuser/src/index.js:50:17)
2021-05-15T22:19:00.552Z     at async /home/myuser/node_modules/apify/build/utils.js:409:20
2021-05-15T22:19:14.808Z Processing https://www.topuniversities.com/university-rankings/world-university-rankings/2020...
2021-05-15T22:19:14.929Z Request https://www.topuniversities.com/university-rankings/world-university-rankings/2020 failed too many times
2021-05-15T22:19:15.155Z INFO: BasicCrawler: All the requests from request list and/or request queue have been processed, the crawler will shut down.
2021-05-15T22:19:15.156Z INFO: Crawler final request statistics: {"avgDurationMillis":null,"perMinute":0,"finished":0,"failed":1,"retryHistogram":[null,null,null,1]}
2021-05-15T22:19:15.214Z Actor finished.

**Comment by pocesar** [comment]
this is fixed in the latest version
